---
- name: Tomcat deployment playbook
  hosts: Tomcat-servers     # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: ubuntu         # Update username for remote server
  roles:
    - Tomcat
